# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d14b60c020739d0533700109287517cb66fccbace6b5e1fb42094ad4a34a0d2eec9bfae3550e0ad4b22b0404a94b334046d3f0f04e98ff0eb63d45dfa936348

test:
  secret_key_base: 74d56592e429ebcffa9faf9e38f6a954f3e1b3d17d69d69830aaf2a2e1a93ff680961571416426fd0b7c059570c774e68a1a1548c08fa3ea41d3f7961f2a05ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
